### ISSUE TITLE
Missing peer dependencies with issue example

### ISSUE THREAD

**Issue by paulyoung** [mjrussell/draft-js-autocomplete-plugin-creator#6]
All of the packages listed as peer dependencies in the root of the project were missing after following the instructions in the README. After installing those in the root I was able to run the example.

I tried installing them in the `examples/issue` directory first but that didn't help.

**Comment by mjrussell** [comment]
What version of NPM are you running (`npm -v`)? More recent versions of NPM dont install peer deps by default which is probably the reason

**Comment by paulyoung** [comment]
I'm using 3.10.8

**Comment by mjrussell** [comment]
Yeah that's why. NPM 2.x would have installed them automatically. Probably the right thing to do is get it so they are listed as deps in the example. I'll have to see if that works. They cannot be listed as deps in the root folder otherwise it will cause collisions when imported. I'm planning to do a little work on this library (merge PRs, etc) this weekend so I'll look then.

**Comment by paulyoung** [comment]
> Probably the right thing to do is get it so they are listed as deps in the example

I tried that and it didn't work for me for some reason. Thanks for looking into it.

**Comment by mjrussell** [comment]
Yeah was tricky...had to do some webpack trickery. Should be fixed now!

**Comment by paulyoung** [comment]
Awesome, thanks!
